### ISSUE TITLE
Media keys

### ISSUE THREAD

**Issue by kacpersledz** [Cloud-Player/desktop-app#4]
Is it possible to implement usage of media keys? For example to play/pause.

**Comment by Zarlex** [comment]
This should actually be working already. Which platform are you using?

**Comment by kacpersledz** [comment]
Systeminfo output:
OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.16299 N/A Build 16299

Also I'm using external keyboard in my laptop (Logitech K280e), in Spotify app media keys are working fine

**Comment by Zarlex** [comment]
Ok thank you for the info. I'm using macOS where it is working fine but i will look for a solution for windows

**Comment by Zarlex** [comment]
Did you have any other application like spotify running when you encountered this issue?
There is the thing in windows that only one application is allowed to get access to the media keys: https://github.com/electron/electron/issues/4702#issuecomment-193689547

**Comment by kacpersledz** [comment]
No, cloud player is the only one running
